# This file stores the xpaths used to parse the xml output files generating after each episode

metrics:
  statistics:
    mean_travel_time: "//vehicleTripStatistics/@duration"
    mean_route_length: "//vehicleTripStatistics/@routeLength"
    mean_speed: "//vehicleTripStatistics/@speed"
    mean_time_loss: "//vehicleTripStatistics/@timeLoss"
    total_travel_time: "//vehicleTripStatistics/@totalTravelTime"
  vehroute:
    vehicles: "//vehicle/@id"
    routes: "//vehicle/route/@edges"
    exit_times: "//vehicle/route/@exitTimes"
