"""
Single source of truth for all file paths used throughout the project.

All paths are derived from BASE_DIR.

Sections
--------
  SUMO inputs              — Common: network config, routes, meandata XML
  SUMO raw outputs         — Common: SUMO XML files written each episode
  Processed SUMO outputs   — Common: parquet versions of raw outputs (tidy format)
  Environment              — Common: agents OD, free-flow costs, time intervals, OD routes, OD matrix
  Experiences              — Common: actions, rewards 
  Agent state              — Algorithm-Specific: agent_debug_trace, results, convergence metric 
  Experiments              — Common: temporary YAML configs for batch runs
  MLflow                   — Common: Backend db, Artifact storage
  Edge Visualization       — Common: Config files used for edge visualization plots
  SA hyperparameters       — Common: Plots and data for plots
  Congestion Simulation    — Common: Files used during process of choosing representative demands for the congestion regimes
  DUE convergence (1)      — Common: Generic files
  DUE convergence (2)      — Algorithm-Specific: R-gap, TDSP, missingness
  API                      — Common: API jobs database

  
Agent state paths are generated via the AgentStatePaths dataclass 
and build_agent_state_paths factory, so algorithms share the same
directory structure under their respective roots without duplicating
path definitions

Most DUE paths are algorithm-specific, and are generated via the 
DuePaths dataclass and build_due_paths factory, so algorithms share the 
same directory structure under their respective roots without 
duplicating path definitions.


Functions
---------
  iter_paths()   — collects every path defined in this file, by scanning
                   its global variables (including paths nested inside
                   dataclasses and lists)
  ensure_dirs()  — creates every directory those paths need, if missing.
                   Call it once at program start

Both functions must live in this file: globals() only sees the variables
of the module where the function is defined.

"""
from dataclasses import fields, is_dataclass
from pathlib import Path

from .paths_helper import (
    ExtraDuaIteratePaths,
    build_agent_state_paths,
    build_due_paths,
)

# ============================================================
# Project root
# ============================================================
# It points to ~/6.Projects/Thesis
BASE_DIR = Path(__file__).resolve().parent.parent.parent



# ============================================================
# SUMO inputs
# ============================================================
# Dir that contains files used by SUMO
SUMO_DIR = BASE_DIR / "sumo"

# Routes XML file needed to simulate traffic (generated every episode)
ROUTES = SUMO_DIR / "routes" / "routes.rou.xml"

# XML SUMO config file needed to carry on simulation
SUMO_CONF = SUMO_DIR / "config" / "basic.sumocfg"

# File that stores xpath expressions used when parsing data
YAML_CONF = BASE_DIR / "src" / "config" / "config.yaml"

# XML file that contains instructions to generate edgeData
MEANDATA = SUMO_DIR / "config" / "meandata.xml"

# Template XML SUMO GUI settings file used for edge visualization
# (color edges by some attribute). Modified to adapt colors range of values
# to the particular case
GUI_SETTINGS = SUMO_DIR / "config" / "gui_settings.xml"



# ============================================================
# SUMO raw outputs
# ============================================================
# Dir that contains all data generated by the simulation (raw XML and processed parquet)
DATA_DIR = BASE_DIR / "data"

# Dir that stores raw data generated by SUMO on each episode
RAW_DATA_DIR = DATA_DIR / "raw"

# File containing the exit times on traversed edges for all vehicles
VEHROUTE_XML = RAW_DATA_DIR / "vehroute.xml"

# File containing statistics aggregated for the entire episode
STATISTICS_XML = RAW_DATA_DIR / "statistics.xml"

# File containing statistics aggregated by timesteps
SUMMARY_XML = RAW_DATA_DIR / "summary.xml"

# File containing statistics aggregated by vehicle
TRIPS_INFO_XML = RAW_DATA_DIR / "tripsinfo.xml"

# File containing statistics aggregated by edge and time intervals
EDGEDATA_XML = RAW_DATA_DIR / "edgedata.xml"

# File containing XY coordinates across all timesteps and vehicles
FCD_XML = RAW_DATA_DIR / "fcd-export.xml"



# ============================================================
# Processed SUMO outputs
# ============================================================
"""
This files are the processed version of the raw files. 
They follow tidy standards and are ready to use for data analysis
"""
# Dir that stores the processed versions of the raw data files (ready to use in data analysis)
PROCESSED_DATA_DIR = DATA_DIR / "processed"
EDGEDATA_PARQUET = PROCESSED_DATA_DIR / "edgedata.parquet"
STATISTICS_PARQUET = PROCESSED_DATA_DIR / "statistics.parquet"
TRIPS_INFO_PARQUET = PROCESSED_DATA_DIR / "trips_info.parquet"
VEHROUTE_PARQUET = PROCESSED_DATA_DIR / "vehroute.parquet"
FCD_PARQUET = PROCESSED_DATA_DIR / "fcd.parquet"



# ============================================================
# Environment
# ============================================================
# Dir that stores files that define the environment used by the learning algorithms
ENVIRONMENT_DIR = DATA_DIR / "environment"

# File containing agents and its ods used throughout the program.
# Post-warm-up agents only — this is what DUE convergence (aggregation.py,
# rgap.py, tdsp.py) joins/reads directly.
AGENTS_OD = ENVIRONMENT_DIR / "agents_od.parquet"

# Debug-only counterpart of AGENTS_OD: every agent, including warm-up ones.
# Not read by any pipeline code — kept around purely for manual inspection.
AGENTS_OD_ALL = ENVIRONMENT_DIR / "agents_od_all.parquet"

# File containing the link free flow travel times
FREE_FLOW_TRAVEL_TIMES = ENVIRONMENT_DIR / "free_flow_travel_times.parquet"

# File containing the times interval table
TIMES_INTERVAL = ENVIRONMENT_DIR / "times_interval.parquet"

# File that contains the available routes for each OD
OD_ROUTES = ENVIRONMENT_DIR / "od_routes.parquet"

# Dir that stores the OD_matrix (represents the demand used to study learning algorithm)
OD_MATRIX_DIR = ENVIRONMENT_DIR / "od_matrix"

# File that contains the OD matrix
OD_MATRIX_TOTAL = OD_MATRIX_DIR / "od_matrix_total.csv"

# File that contains the OD matrix across intervals
OD_MATRIX_INTERVALS = OD_MATRIX_DIR / "od_matrix_intervals.csv"



# ============================================================
# Experiences
# ============================================================
# Dir that stores files related to the experiences across episodes
EXPERIENCES_DIR = DATA_DIR / "experiences"

# File containing actions of agents across episodes
ACTIONS = EXPERIENCES_DIR / "actions.parquet"

# File containing rewards of agents across episodes
REWARDS = EXPERIENCES_DIR / "rewards.parquet"



# ============================================================
# Agent state - algorithm-specific 
# ============================================================
# Files: (agent_debug_trace, results, convergence_metric)

# 1. Bush-Mosteller (BM)
BM_STATE_PATHS = build_agent_state_paths(DATA_DIR / "agent_state" / "BM")
# 2. Q-learning, Thompson Sampling...



# ============================================================
# Experiments
# ============================================================
"""
Directory containing temporal experiment-specific YAML configuration files.

During grid search, a YAML template is copied and updated with the
hyperparameter values of the current parameter combination. The resulting
configuration file is stored here and used to run the experiment.
"""
EXPERIMENTS_TMP = BASE_DIR / "experiments" / "tmp"



# ============================================================
# MLFlow database
# ============================================================

# File that stores metadata about runs (parameters, metrics...)
BACKEND_DB = BASE_DIR / "mlflow_db" / "mlflow.db"

# Dir that stores artifacts across runs
ARTIFACTS_STORAGE = "mlruns/mlruns"



# ============================================================
# Edge visualization
# ============================================================

# Dir that contains files needed to run the simulation with edge visualization (coloring by some attribute)
EDGE_VISUALIZATION_DIR = SUMO_DIR / "config" / "edge_visualization"

# SUMO config file used to run the simulation with edge visualization (coloring by some attribute)
SUMO_CONF_AGGREGATED = EDGE_VISUALIZATION_DIR / "aggregated.sumocfg"

# SUMO GUI settings generated from updating the colors range values from template GUI setting file
GUI_SETTINGS_AGGREGATED = EDGE_VISUALIZATION_DIR / "gui_settings_aggregated.xml"

# Meandata file used to decide if edges values are aggregated over time interval
# or not (the whole episode). Hence, decides if generate edge visualization for each interval or for the whole episode
MEANDATA_AGGREGATED = EDGE_VISUALIZATION_DIR / "meandata_aggregated.xml"



# ============================================================
# SA hyperparameters
# ============================================================
# Plots
SENSITIVITY_PLOTS_DIR = BASE_DIR / "src/tools/sensitivity/output"
# Generated data for the plots
SENSITIVITY_RESULTS_DIR = BASE_DIR / "src/tools/sensitivity/results"



# ============================================================
# Congestion simulation
# ============================================================

# Dir that contains files used by the congestion simulator (sensitivity tools)
CONGESTION_SIM_DIR = SUMO_DIR / "congestion_sim"

# File that contains the trips
TRIPS_CONGESTION_SIM = CONGESTION_SIM_DIR / "trips.xml"

# File that stores the routes (shortest paths)
ROUTES_CONGESTION_SIM = CONGESTION_SIM_DIR / "routes.xml"

# SUMO Config file needed for simulation
SUMO_CONF_CONGESTION_SIM = CONGESTION_SIM_DIR / "basic.cfg"

ROUTES_FREE_FLOW = CONGESTION_SIM_DIR / "ff_routes.xml"
SUMO_CONF_FREE_FLOW = CONGESTION_SIM_DIR / "ff.cfg"
TRIPS_INFO_FREE_FLOW = CONGESTION_SIM_DIR / "ff_tripsinfo.xml"



# ============================================================
# DUE convergence (1) (common)
# ============================================================
# Dir that stores files used on DUE convergence checks
DUE_DATA_DIR = DATA_DIR / "DUE"

# Dir that stores generic files used on DUE convergence checks
DUE_DATA_generic = DUE_DATA_DIR / "generic"

# XML File defining the Cartesian product of time intervals, and OD pairs
# used to compute their time_dependent shortest path by TDSP
TRIPS_TDSP = DUE_DATA_generic / "trips.xml"

# Parquet version of the OD matrix by interval
DEMAND_ODT = DUE_DATA_generic / "demand_odt.parquet"



# ============================================================
# DUE convergence (2) (algorithm-specific)
# ============================================================
# 1. duaIterate
DUE_DUAITERATE = DUE_DATA_DIR / "duaIterate"
DUAITERATE_DUE_PATHS = build_due_paths(DUE_DUAITERATE)
DUAITERATE_DUE_EXTRA = ExtraDuaIteratePaths(
    mean_tt=DUE_DUAITERATE / "mean_tt.parquet",
    trips=DUE_DUAITERATE / "trips.xml",
    od_routes=DUE_DUAITERATE / "od_routes.parquet",
    actions=DUE_DUAITERATE / "actions.parquet",
    trips_info_processed=DUE_DUAITERATE / "trips_info_processed.parquet",
    vehroute_processed=DUE_DUAITERATE / "vehroute.parquet",
    edgedata_processed=DUE_DUAITERATE / "edgedata" / "edgedata.parquet",
    routes=DUE_DUAITERATE / "routes_last_iteration.rou.xml",
)
# When calling DuaIterate some undesired additional files are generated
UNDESIRED_ROUTE_FILE = BASE_DIR / "routes.rou.xml"
UNDESIRED_duaIterate_FILES = [
    BASE_DIR / "dua.log",
    BASE_DIR / "stdout.log",
    BASE_DIR / "edgedata.add.xml",
]
# 2. Bush-Mosteller (BM)
BM_DUE_DIR = DUE_DATA_DIR / "BM"
BM_DUE_PATHS = build_due_paths(BM_DUE_DIR)
# Routes file (.rou.xml) of last training episode, copied out of the
# ephemeral SUMO working file (ROUTES) so it survives as an MLflow artifact.
# Used for the sumo-gui edge-visualization replay (RQ7).
ROUTES_LAST_EPISODE_BM = BM_DUE_DIR / "routes_last_episode.rou.xml"

# ============================================================
# API
# ============================================================
JOBS_DB = BASE_DIR / "api_db" / "jobs.db"


###########
# FUNCTIONS
###########

def iter_paths() -> list[Path]:
    """Returns a list with all the paths defined in this module, including ones nested
    inside dataclass instances (AgentStatePaths, DuePaths, ExtraDuaIteratePaths) and lists."""
    
    paths = []

    # Globals() returns all the objects defined in the global namespace of this module
    # In the global namespace, there is not only user-defined variables, but also
    # internal variables like __name__, __doc__...
    for value in globals().values():
        # 1. Single variable
        if isinstance(value, Path):
            paths.append(value)
        # 2. List or tuple
        elif isinstance(value, (list, tuple)):
            for item in value:
                if isinstance(item, Path):
                    paths.append(item)
        # 3. Dataclass fields
        elif is_dataclass(value) and not isinstance(value, type):
            for field in fields(value):
                item = getattr(value, field.name)
                if isinstance(item, Path):
                    paths.append(item)
    return paths


def ensure_dirs() -> None:
    """Create every directory implied by the paths in this module, if missing."""
    paths = iter_paths()

    # Get all directories used to store data
    dirs = {path.parent if path.suffix else path for path in paths}
    for directory in dirs:
        # If directory does not exist create. If it does, nothing happens
        directory.mkdir(parents=True, exist_ok=True)