"""
Single source of truth for all file paths used throughout the project.

All paths are derived from BASE_DIR.

Sections
--------
  SUMO files          — network config, routes, meandata XML
  Demand calibration  — trips, routes, config for the calibration loop
  Raw outputs         — SUMO XML files written each episode
  Processed outputs   — parquet versions of raw outputs (tidy format)
  Agent state         — actions, rewards, BM internal state across episodes
  Environment         — agents OD, free-flow costs, time intervals, OD routes
  DUE convergence     — R-gap, TDSP, missingness files for BM and duaIterate
  MLflow              — database, artifact store, run id file
  Experiments         — temporary YAML configs for batch runs

DUE paths are generated via the DuePaths dataclass and _due_paths()
factory, so BM and duaIterate share the same directory structure under
their respective roots without duplicating path definitions.
"""

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DuePaths:
    """
    Files generated when running DUE convergence checks (blueprint to avoid duplication)

    Structure:
    - TDSP/: Time-dependent shortest path data
    - R-gap/: Equilibrium convergence metrics
    - missingness/: Route coverage statistics

    Attributes
    ----------
    root
        Algorithms base dir

    tdsp_dir
        Dir that stores files used when computing tdsp

    rgap_dir
        Dir that stores the rgap metrics

    missingness_dir
        Dir that stores the missingness analysis of
        the avg travel times of links table

    weights_dir
        Dir that stores the xml files related to time dependent link costs,
        for every episode, used by duarouter to compute tdsp

    shortest_paths_dir
        Dir that stores the xml files with the
        time dependent shortest paths generated by duarouter

    flows_paths
        File that contains flows for every path across episodes and time_intervals

    cost_paths
        File that contains the avg cost of every path across episodes and time_intervals

    cost_links
        File that contains the avg cost of every link across episodes and time_intervals

    cost_min_paths
        File that contains the cost of the time dependent shortest path across episodes and time_intervals

    rgap
        File that contains the rgap across episodes

    refined_rgap
        File that contains the rgap across episodes and time intervals

    missingness_int
        File that contains the missing values by interval
        in the avg travel time link table

    missingness_edge
        File that contains the missing values by edge
        in the avg travel time link table

    missingness_int
        File that contains the missing values by episode
        in the avg travel time link table

    missingness_report
        File that contains the absolute and relative count of missign values
    """

    root: Path
    tdsp_dir: Path
    rgap_dir: Path
    missingness_dir: Path
    weights_dir: Path
    shortest_paths_dir: Path
    flows_paths: Path
    cost_paths: Path
    cost_links: Path
    cost_min_paths: Path
    rgap: Path
    refined_rgap: Path
    rgap_by_od: Path
    refined_rgap_by_od: Path
    missingness_int: Path
    missingness_edge: Path
    missingness_episode: Path
    missingness_report: Path


def _due_paths(algorithm_root: Path) -> DuePaths:
    """
    Factory that builds for a given algorithm all the paths
    required by Dataclass DuePaths automatically
    """
    tdsp = algorithm_root / "TDSP"
    rgap = algorithm_root / "R-gap"
    missingness = algorithm_root / "missingness"
    return DuePaths(
        root=algorithm_root,
        tdsp_dir=tdsp,
        rgap_dir=rgap,
        missingness_dir=missingness,
        weights_dir=tdsp / "weights",
        shortest_paths_dir=tdsp / "shortest_paths",
        flows_paths=algorithm_root / "flows_paths_odtp_k.parquet",
        cost_paths=algorithm_root / "costs_paths_odtp_k.parquet",
        cost_links=tdsp / "costs_links_t_k.parquet",
        cost_min_paths=tdsp / "costs_min_paths_t_k.parquet",
        rgap=rgap / "rgap.parquet",
        refined_rgap=rgap / "refined_rgap.parquet",
        rgap_by_od=rgap / "rgap_by_od.parquet",
        refined_rgap_by_od=rgap / "refined_rgap_by_od.parquet",
        missingness_int=missingness / "missingness_by_int.parquet",
        missingness_edge=missingness / "missingness_by_edge.parquet",
        missingness_episode=missingness / "missingness_by_episode.parquet",
        missingness_report=missingness / "missingness_report.txt",
    )


@dataclass(frozen=True)
class DuaIteratePaths:
    """
    Extra files generated specifically for DuaIterate algorithm
    when running DUE convergence checks on it

    Attributes
    ----------

    mean_tt
        File that contains the mean travel time across DuaIterate iterations

    trips
        XML file that contains the trips used by DuaIterate
        (only contains the trips, not the routes)

    routes
        XML file that contains the routes computed by DuaIterate
        for every vehicle

    od_routes
        File that contains the routes used for each od
        in the last DuaIterate iteration

    actions
        File that contains the idx of the route chosen by each driver
        in the last DuaIterate iteration
        (this idx is relative to the od_routes data structure)

    trips_info_processed
        File that contains the trip info for each vehicle
        in the last DuaIterate iteration

    vehroute_processed
        File that contains the exit time on each edge the driver traversed,
        for all drivers
        (in the last DuaIterate iteration)

    edgedata_processed
        File that contains info about edges across interval and episodes
        (in the last DuaIterate iteration)
    """

    mean_tt: Path
    trips: Path
    routes: Path
    od_routes: Path
    actions: Path
    trips_info_processed: Path
    vehroute_processed: Path
    edgedata_processed: Path


# ============================================================
# Project root
# ============================================================

# It points to ~/6.Projects/Thesis
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ============================================================
# MLFlow database
# ============================================================

# File that stores metadata about runs (parameters, metrics...)
BACKEND_DB = BASE_DIR / "mlflow_db" / "mlflow.db"

# Dir that stores artifacts across runs
ARTIFACTS_STORAGE = BASE_DIR / "mlruns" / "mlruns"

# ============================================================
# Main folders
# ============================================================

# Dir that contains all data generated by the simulation (raw XML and processed parquet)
DATA_DIR = BASE_DIR / "data"

# Dir that stores raw data generated by SUMO on each episode
RAW_DATA_DIR = DATA_DIR / "raw"

# Dir that stores the processed versions of the raw data files (ready to use in data analysis)
PROCESSED_DATA_DIR = DATA_DIR / "processed"

# Dir that stores the OD_matrix (represents the demand used to study learning algorithm)
OD_MATRIX_DIR = DATA_DIR / "od_matrix"

# File that contains the OD matrix
OD_MATRIX_TOTAL = OD_MATRIX_DIR / "od_matrix_total.csv"

# File that contains the OD matrix across intervals
OD_MATRIX_INTERVALS = OD_MATRIX_DIR / "od_matrix_intervals.csv"

# Dir that stores files that define the environment used by the learning algorithms
ENVIRONMENT_DIR = DATA_DIR / "environment"

# Dir that contains files used by SUMO
SUMO_DIR = BASE_DIR / "sumo"

# Dir that contains profiles of the program
PROFILING_DIR = BASE_DIR / "profiling"

# ============================================================
# SUMO files
# ============================================================

# Routes XML file needed to simulate traffic (generated every episode)
ROUTES = SUMO_DIR / "routes" / "routes.rou.xml"

# XML SUMO config file needed to carry on simulation
SUMO_CONF = SUMO_DIR / "config" / "basic.sumocfg"

# Template XML SUMO GUI settings file used for edge visualization
# (color edges by some attribute). Modified to adapt colors range of values
# to the particular case
GUI_SETTINGS = SUMO_DIR / "config" / "gui_settings.xml"

# XML file that contains instructions to generate edgeData
MEANDATA = SUMO_DIR / "config" / "meandata.xml"

# File that stores xpath expressions used when parsing data
YAML_CONF = BASE_DIR / "src" / "config" / "config.yaml"

# ============================================================
# Demand calibration
# ============================================================

# Dir that contains files used during demand_calibration
DEMAND_CALIBRATION_DIR = SUMO_DIR / "demand_calibration"

# File that contains the trips (demand calibration)
TRIPS_DEMAND_CALIBRATION = DEMAND_CALIBRATION_DIR / "trips.xml"

# File that stores the routes (shortest paths) (demand calibration)
ROUTES_DEMAND_CALIBRATION = DEMAND_CALIBRATION_DIR / "routes.xml"

# SUMO Config file needed for simulation (demand calibration)
SUMO_CONF_DEMAND_CALIBRATION = DEMAND_CALIBRATION_DIR / "basic.cfg"

# Free-flow simulation: one vehicle per unique route on an empty network,
# used to obtain accurate route-level free-flow travel times
ROUTES_FREE_FLOW = DEMAND_CALIBRATION_DIR / "ff_routes.xml"
SUMO_CONF_FREE_FLOW = DEMAND_CALIBRATION_DIR / "ff.cfg"
TRIPS_INFO_FREE_FLOW = DEMAND_CALIBRATION_DIR / "ff_tripsinfo.xml"

# ============================================================
# Sensitivity
# ============================================================
SENSITIVITY_PLOTS_DIR = BASE_DIR / "src/tools/sensitivity/output"

# ============================================================
# SUMO raw outputs
# ============================================================

# File containing the exit times on traversed edges for all vehicles
VEHROUTE_XML = RAW_DATA_DIR / "vehroute.xml"

# File containing statistics aggregated for the entire episode
STATISTICS_XML = RAW_DATA_DIR / "statistics.xml"

# File containing statistics aggregated by timesteps
SUMMARY_XML = RAW_DATA_DIR / "summary.xml"

# File containing statistics aggregated by vehicle
TRIPS_INFO_XML = RAW_DATA_DIR / "tripsinfo.xml"

# File containing statistics aggregated by edge and time intervals
EDGEDATA_XML = RAW_DATA_DIR / "edgedata.xml"

# File containing XY coordinates across all timesteps and vehicles
FCD_XML = RAW_DATA_DIR / "fcd-export.xml"


# ============================================================
# Processed outputs
# ============================================================

"""
This files are the processed version of the raw files. 
They follow tidy standards and are ready to use for data analysis
"""
EDGEDATA_PARQUET = PROCESSED_DATA_DIR / "edgedata.parquet"
STATISTICS_PARQUET = PROCESSED_DATA_DIR / "statistics.parquet"
TRIPS_INFO_PARQUET = PROCESSED_DATA_DIR / "trips_info.parquet"
VEHROUTE_PARQUET = PROCESSED_DATA_DIR / "vehroute.parquet"
FCD_PARQUET = PROCESSED_DATA_DIR / "fcd.parquet"

# ============================================================
# Internal agents data
# ============================================================
# Dir that stores files related to the agents state across episodes
AGENT_STATE_DIR = DATA_DIR / "agent_state"

# File containing policy changes of BM agents across episodes
POLICY_CHANGE_BM = AGENT_STATE_DIR / "policy_change_BM.parquet"

# File containing actions of BM agents across episodes
ACTIONS = AGENT_STATE_DIR / "actions.parquet"

# File containing rewards of BM agents across episodes
REWARDS = AGENT_STATE_DIR / "rewards.parquet"

# File containing BM data (stimulus, expected travel time...) across agents and episodes
BM_RESULTS = AGENT_STATE_DIR / "BM_results.parquet"

# ============================================================
# Internal environment data
# ============================================================

# File containing agents and its ods used throughout the program
AGENTS_OD = ENVIRONMENT_DIR / "agents_od.parquet"

# File containing the link free flow travel times
FREE_FLOW_TRAVEL_TIMES = ENVIRONMENT_DIR / "free_flow_travel_times.parquet"

# File containing the times interval table
TIMES_INTERVAL = ENVIRONMENT_DIR / "times_interval.parquet"

# File that contains the available routes for each OD
OD_ROUTES = ENVIRONMENT_DIR / "od_routes.parquet"

# ============================================================
# Algorithms paths (used in DUE convergence checks)
# ============================================================
# PARENT
# Dir that stores files used on DUE convergence checks
DUE_DATA_DIR = DATA_DIR / "DUE"

# CHILDS
# Dir that stores specific BM files used on DUE convergence checks
DUE_DATA_BM = DUE_DATA_DIR / "BM"

# Dir that stores specific DuaIterate files used on DUE convergence checks
DUE_DATA_duaIterate = DUE_DATA_DIR / "duaIterate"

BM_PATHS = _due_paths(DUE_DATA_BM)
DUA_PATHS = _due_paths(DUE_DATA_duaIterate)
DUA_EXTRA = DuaIteratePaths(
    mean_tt=DUE_DATA_duaIterate / "mean_tt.parquet",
    trips=DUE_DATA_duaIterate / "trips.xml",
    routes=SUMO_DIR / "routes" / "routes_duaIterate.rou.xml",
    od_routes=DUE_DATA_duaIterate / "od_routes.parquet",
    actions=DUE_DATA_duaIterate / "actions.parquet",
    trips_info_processed=DUE_DATA_duaIterate / "trips_info_processed.parquet",
    vehroute_processed=DUE_DATA_duaIterate / "vehroute.parquet",
    edgedata_processed=DUE_DATA_duaIterate / "edgedata" / "edgedata.parquet",
)

# ============================================================
# Generic files (used in DUE convergence checks)
# ============================================================
# Dir that stores generic files used on DUE convergence checks
DUE_DATA_generic = DUE_DATA_DIR / "generic"

# XML File defining the Cartesian product of time intervals, and OD pairs
# used to compute their time_dependent shortest path by TDSP
TRIPS_TDSP = DUE_DATA_generic / "trips.xml"

# Parquet version of the OD matrix by interval
DEMAND_ODT = DUE_DATA_generic / "demand_odt.parquet"

# ============================================================
# Temporary/generated files
# ============================================================
# When calling DuaIterate some undesired additional files are generated

UNDESIRED_ROUTE_FILE = BASE_DIR / "routes.rou.xml"

UNDESIRED_duaIterate_FILES = [
    BASE_DIR / "dua.log",
    BASE_DIR / "stdout.log",
    BASE_DIR / "edgedata.add.xml",
]

# ============================================================
# Edge visualization
# ============================================================

# Dir that contains files needed to run the simulation with edge visualization (coloring by some attribute)
EDGE_VISUALIZATION_DIR = SUMO_DIR / "config" / "edge_visualization"

# SUMO config file used to run the simulation with edge visualization (coloring by some attribute)
SUMO_CONF_AGGREGATED = EDGE_VISUALIZATION_DIR / "aggregated.sumocfg"

# SUMO GUI settings generated from updating the colors range values from template GUI setting file
GUI_SETTINGS_AGGREGATED = EDGE_VISUALIZATION_DIR / "gui_settings_aggregated.xml"

# Meandata file used to decide if edges values are aggregated over time interval
# or not (the whole episode). Hence, decides if generate edge visualization for each interval or for the whole episode
MEANDATA_AGGREGATED = EDGE_VISUALIZATION_DIR / "meandata_aggregated.xml"

# ============================================================
# MLFLOW
# ============================================================
# File that stores the run id of the simulation run
MLFLOW_SOURCE_RUN_ID = DATA_DIR / "MLflow" / "source_run_id.txt"

# ============================================================
# EXPERIMENTS
# ============================================================
"""
Directory containing temporal experiment-specific YAML configuration files.

During grid search, a YAML template is copied and updated with the
hyperparameter values of the current parameter combination. The resulting
configuration file is stored here and used to run the experiment.
"""
EXPERIMENTS_TMP = BASE_DIR / "experiments" / "tmp"
