"""
Helpers behind paths.py: the machinery for building and creating paths
for different algorithms (enforcing the same structure)

Contents
--------
  Dataclasses  — blueprints of the files every algorithm writes
                 (DuePaths, AgentStatePaths) and the extra files only
                 duaIterate writes (ExtraDuaIteratePaths)
  Factories    — build_due_paths() and build_agent_state_paths() fill a
                 blueprint for one algorithm, given its root directory

Adding a new algorithm
----------------------
Nothing changes here. In paths.py, pick a root directory for the algorithm
and call each factory with it, e.g.

    QL_STATE_PATHS = build_agent_state_paths(DATA_DIR / "agent_state" / "QL")
    QL_PATHS = build_due_paths(DUE_DATA_DIR / "QL")

Each algorithm then gets the same file layout under its own root, so
files with an algorithm-specific schema never share a path.
"""

from dataclasses import dataclass
from pathlib import Path

###########
# DATACLASSES AND FACTORIES
###########


@dataclass(frozen=True)
class DuePaths:
    """
    Files generated when running DUE convergence checks (blueprint to avoid duplication)

    Structure:
    - TDSP/: Time-dependent shortest path data
    - R-gap/: Equilibrium convergence metrics
    - missingness/: Route coverage statistics

    Attributes
    ----------
    root
        Root dir of this algorithm's DUE files

    tdsp_dir
        Dir that stores files used when computing tdsp

    rgap_dir
        Dir that stores the rgap metrics

    missingness_dir
        Dir that stores the missingness analysis of
        the avg travel times of links table

    weights_dir
        Dir that stores the xml files related to time dependent link costs,
        for every episode, used by duarouter to compute tdsp

    shortest_paths_dir
        Dir that stores the xml files with the
        time dependent shortest paths generated by duarouter

    flows_paths
        File that contains flows for every path across episodes and time_intervals

    cost_paths
        File that contains the avg cost of every path across episodes and time_intervals

    cost_links
        File that contains the avg cost of every link across episodes and time_intervals

    cost_min_paths
        File that contains the cost of the time dependent shortest path across episodes and time_intervals

    rgap
        File that contains the rgap across episodes

    refined_rgap
        File that contains the rgap across episodes and time intervals

    rgap_by_od
        File that contains the rgap across episodes and OD pairs

    refined_rgap_by_od
        File that contains the rgap across episodes, OD pairs and time intervals

    missingness_int
        File that contains the missing values by interval
        in the avg travel time link table

    missingness_edge
        File that contains the missing values by edge
        in the avg travel time link table

    missingness_episode
        File that contains the missing values by episode
        in the avg travel time link table

    missingness_report
        File that contains the absolute and relative count of missing values
    """

    root: Path
    tdsp_dir: Path
    rgap_dir: Path
    missingness_dir: Path
    weights_dir: Path
    shortest_paths_dir: Path
    flows_paths: Path
    cost_paths: Path
    cost_links: Path
    cost_min_paths: Path
    rgap: Path
    refined_rgap: Path
    rgap_by_od: Path
    refined_rgap_by_od: Path
    missingness_int: Path
    missingness_edge: Path
    missingness_episode: Path
    missingness_report: Path


@dataclass(frozen=True)
class AgentStatePaths:
    """
    Files with different schema across algorithms

    Attributes
    ----------
    root
        Root dir of this algorithm's agent state files
    
    agent_debug_trace
        File that contains all necessary info to debug a single agent learning process
        (e.g. Bush-Mosteller -> (history, p, ET, PT, stimulus) across episodes)

    results
        File containing all the relevant quantities of the particular learning algorithm
        across all agents and episodes
        (e.g. Bush-Mosteller -> (stimulus, expected travel time...)) 
    
    convergence_metric 
        File containing the convergence metric across agents and episodes used in the 
        stopping rule to determine when the MARL algorithm should stop
        (e.g. Bush-Mosteller -> policy changes of agents across episodes)

    """

    root: Path
    agent_debug_trace: Path
    results: Path
    convergence_metric: Path


def build_due_paths(algorithm_root: Path) -> DuePaths:
    """
    Factory that builds for a given algorithm all the paths
    required by Dataclass DuePaths automatically
    """
    tdsp = algorithm_root / "TDSP"
    rgap = algorithm_root / "R-gap"
    missingness = algorithm_root / "missingness"
    return DuePaths(
        root=algorithm_root,
        tdsp_dir=tdsp,
        rgap_dir=rgap,
        missingness_dir=missingness,
        weights_dir=tdsp / "weights",
        shortest_paths_dir=tdsp / "shortest_paths",
        flows_paths=algorithm_root / "flows_paths_odtp_k.parquet",
        cost_paths=algorithm_root / "costs_paths_odtp_k.parquet",
        cost_links=tdsp / "costs_links_t_k.parquet",
        cost_min_paths=tdsp / "costs_min_paths_t_k.parquet",
        rgap=rgap / "rgap.parquet",
        refined_rgap=rgap / "refined_rgap.parquet",
        rgap_by_od=rgap / "rgap_by_od.parquet",
        refined_rgap_by_od=rgap / "refined_rgap_by_od.parquet",
        missingness_int=missingness / "missingness_by_int.parquet",
        missingness_edge=missingness / "missingness_by_edge.parquet",
        missingness_episode=missingness / "missingness_by_episode.parquet",
        missingness_report=missingness / "missingness_report.txt",
    )


def build_agent_state_paths(algorithm_root: Path) -> AgentStatePaths:
    """
    Factory that builds for a given algorithm all the paths
    required by Dataclass AgentStatePaths automatically
    """
    return AgentStatePaths(
        root=algorithm_root,
        agent_debug_trace=algorithm_root / "agent_debug_trace.json",
        results=algorithm_root / "results.parquet",
        convergence_metric=algorithm_root / "convergence_metric.parquet",
    )


@dataclass(frozen=True)
class ExtraDuaIteratePaths:
    """
    Extra files generated specifically for DuaIterate algorithm
    when running DUE convergence checks on it

    Attributes
    ----------

    mean_tt
        File that contains the mean travel time across DuaIterate iterations

    trips
        XML file that contains the trips used by DuaIterate
        (only contains the trips, not the routes)

    od_routes
        File that contains the routes used for each od
        in the last DuaIterate iteration

    actions
        File that contains the idx of the route chosen by each driver
        in the last DuaIterate iteration
        (this idx is relative to the od_routes data structure)

    trips_info_processed
        File that contains the trip info for each vehicle
        in the last DuaIterate iteration

    vehroute_processed
        File that contains the exit time on each edge the driver traversed,
        for all drivers
        (in the last DuaIterate iteration)

    edgedata_processed
        File that contains info about edges across interval and episodes
        (in the last DuaIterate iteration)

    routes
        Routes file (.rou.xml) generated by the last DuaIterate iteration,
        copied out before its scratch folder is deleted. Used for the
        sumo-gui edge-visualization replay (RQ7).
    """

    mean_tt: Path
    trips: Path
    od_routes: Path
    actions: Path
    trips_info_processed: Path
    vehroute_processed: Path
    edgedata_processed: Path
    routes: Path