"""
One-off tool: sweeps a range of demand levels, measures the congestion metric
for each, and automatically selects a representative demand value for each
congestion regime.

Congestion metric
-----------------
The congestion metric is the average ratio of actual to free-flow trip duration:

    congestion_metric = (1/N) * sum( T_i / T_i_free )  for i = 1..N agents

where T_i is the actual trip duration and T_i_free is the free-flow shortest-path
duration under an empty network. A value of 1.4 means trips take on average 40%
longer than free-flow. The metric is dimensionless and monotonically increasing
with congestion level.

Free-flow travel times
-------------------------------------
It should be noted, that the true free-flow travel time of an edge is not the same than
dividing the edge length by its maximum speed. Because the true free flow travel time
takes into account the acceleration, deceleration... Hence, the edge length / max speed, can
be seen as an estimate, but its not the true value. That estimate underestimates the true free
flow travel time value and hence it overestimates the congestion metric.
Because, even with an empty network, the congestion metric was taking values of 1.4~1.5, the true
free flow travel times were generated by running a simulation with almost no vehicles, and then the
ratio takes value of 1 for very low demands as it should.


Congestion regimes and decision rule
-------------------------------------
Two congestion regimes are defined (low, severe) via threshold lower bounds stored
in CONGESTION_REGIMES. These thresholds are qualitative and somewhat arbitrary —
what matters is that they produce meaningfully distinct traffic states for the
experiments. For each regime, the representative demand is selected as the first
demand value where the metric exceeds the regime threshold and the immediately
following demand value also stays above it. This two-point rule avoids picking a
noisy spike that immediately drops back below the threshold.

The representative demands selected here are used throughout the thesis experiments
to evaluate the MARL algorithm's performance under different congestion levels.

Demand grid
-----------
The demand sweep range (DEMANDS) must be set manually per network before running.
The lower bound should start at or just below the onset of congestion, not at the
free-flow baseline — sweeping demands that produce identical free-flow results wastes
simulation runs without adding information. The upper bound should be high enough
to clearly reach heavy congestion, but not much beyond that: once the representative
demand for the highest regime has been identified, additional points yield no useful
information and only increase runtime. The step size trades resolution against runtime.

The script otherwise runs automatically: it sweeps demands, plots the congestion
curve with regime bands and threshold lines, and marks the selected representative
demands directly on the plot.

Run with: python src/tools/sensitivity/plot_congestion_metric.py <config.yaml>
"""

import sys
from pathlib import Path

import matplotlib.pyplot as plt

plt.style.use(Path(__file__).parent / "thesis_style.mplstyle")
import numpy as np

# Workaround paths when import
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from config.config import config
from config.paths import SENSITIVITY_PLOTS_DIR
from demand_calibration.demand_calibration import DemandCalibration
from utils.generate_agents import build_od_space, generate_agents_from_od_space

# CONSTANTS
SEEDS = [42, 123, 1999, 2026]

# Adjust per network: lower bound should cover free-flow, upper bound should
# reach heavy congestion. Step size trades resolution against runtime.
DEMANDS = range(1000, 5000, 100)

# Congestion regime thresholds (lower bound, label, band color, accent color for markers)
CONGESTION_REGIMES = [
    (1.0, "Free-flow", "#d9f0a3", None),
    (1.2, "Moderate congestion", "#fecc5c", "#c05800"),
    (2.0, "High congestion", "#fd8d3c", "#a82000"),
]


def main():

    for seed in SEEDS:
        # 0. Container
        result = []
        accumulated_agents = []
        prev_demand = 0

        # 1. Build one shared OD space for this seed, using the outer seed so
        #    different SEEDS entries get distinct OD pools from randomTrips.
        rng = np.random.default_rng(seed)
        od_space = build_od_space(max(DEMANDS), seed=seed)

        for demand in DEMANDS:

            # 2. Log
            print("\n##########")
            print(f"# {demand}")
            print("##########")

            # 2. Generate only the incremental agents for this demand step so that
            #    demand=N is always a strict superset of demand=N-step (nested demands).
            delta = demand - prev_demand
            delta_agents, _ = generate_agents_from_od_space(od_space, delta, rng)
            accumulated_agents.extend(delta_agents)

            # 3. Sort agents data structure by departure time
            accumulated_agents.sort(key=lambda a: a["departure_time"])

            # 4. Re-number IDs so DemandCalibration sees a consistent sequence.
            agents_for_sim = [
                {**a, "id": f"agent_{i + 1}"} for i, a in enumerate(accumulated_agents)
            ]

            # 5. Get metric value
            demand_calibration = DemandCalibration(config.network, agents_for_sim)
            congestion_metric_value = demand_calibration.compute_congestion_metric()

            # 6. Store
            result.append(
                {"demand": demand, "congestion_metric": congestion_metric_value},
            )
            prev_demand = demand

        # 5. Plot
        _make_plot(result, seed)


def _find_representative_demand(demands, values, threshold):
    """First demand where the metric exceeds threshold and the next point also stays above."""
    for i in range(len(values) - 1):
        if values[i] > threshold and values[i + 1] > threshold:
            return demands[i]
    return None


def _make_plot(result, seed):

    # 1. Manage path
    network_name = Path(config.network).stem
    plot_prefix = "congestion_metric_"
    path = SENSITIVITY_PLOTS_DIR / f"{plot_prefix}{network_name}_{seed}.png"

    # 2. Extract values
    demands = [r["demand"] for r in result]
    congestion_metric_values = [r["congestion_metric"] for r in result]

    # 3. Create figure
    fig, ax = plt.subplots()

    # 4. Set upper limit y-axis
    q1 = np.percentile(congestion_metric_values, 25)
    q3 = np.percentile(congestion_metric_values, 75)
    iqr = q3 - q1
    y_cap = q3 + 1.5 * iqr
    ax.set_ylim(1, y_cap)

    # 5. Draw regime bands and threshold lines
    thresholds = [y for y, *_ in CONGESTION_REGIMES]
    for i, (y_lo, label, color, _) in enumerate(CONGESTION_REGIMES):
        if y_lo >= y_cap:
            break
        y_hi = thresholds[i + 1] if i + 1 < len(thresholds) else y_cap
        y_hi = min(y_hi, y_cap)
        ax.axhspan(y_lo, y_hi, color=color, alpha=0.25, zorder=0)
        ax.text(
            0.01,
            (y_lo + y_hi) / 2,
            label,
            transform=ax.get_yaxis_transform(),
            va="center",
            ha="left",
            fontsize=8,
            color="0.4",
        )
        if y_lo > 1:
            ax.axhline(y_lo, color="0.6", linestyle="--", linewidth=0.6, zorder=1)

    # 6. Mark representative demands with vertical lines
    for y_lo, label, _, accent in CONGESTION_REGIMES[1:]:  # skip free-flow
        demand = _find_representative_demand(demands, congestion_metric_values, y_lo)
        if demand is not None:
            ax.axvline(demand, color=accent, linestyle="--", linewidth=1.2, zorder=2)
            ax.text(
                demand,
                y_lo,
                f"{label}\n{demand} veh",
                va="bottom",
                ha="center",
                fontsize=6,
                color="0.15",
                bbox=dict(
                    boxstyle="round,pad=0.15",
                    facecolor="white",
                    edgecolor=accent,
                    linewidth=0.8,
                    alpha=0.8,
                ),
                zorder=4,
            )

    # 7. Draw curve
    ax.plot(
        demands,
        congestion_metric_values,
        marker="o",
        linewidth=2,
        markersize=4,
        zorder=2,
    )

    # 8. Outliers annotations
    clipped = [(d, v) for d, v in zip(demands, congestion_metric_values) if v > y_cap]

    for demand, _ in clipped:
        ax.plot(
            demand, y_cap, marker="^", color="C0", markersize=6, clip_on=False, zorder=3
        )

    # 9. Improve visualization
    ax.set_xlabel("Demand (vehicles)")
    ax.set_ylabel("Congestion metric")
    ax.set_title(f"Congestion metric vs demand — seed {seed} ({network_name})")

    # Add 1.2 to y-ticks (2.0 already lands on a default tick)
    ticks = sorted(set(list(ax.get_yticks()) + [1.2]))
    ax.set_yticks([t for t in ticks if 1 <= t <= y_cap])

    # Outlier count note
    if clipped:
        ax.text(
            0.01,
            0.99,
            f"▲ {len(clipped)} value(s) exceed the y-axis limit",
            transform=ax.transAxes,
            va="top",
            ha="left",
            fontsize=7,
            color="0.45",
            style="italic",
        )

    # 8. Save
    fig.tight_layout()
    fig.savefig(path)


if __name__ == "__main__":
    main()
