configuration_name:
  config_name: production

randomness:
  seed: 42

numerical_constants:
  epsilon: 1.0e-8

learning:
  learning_rate: 0.3
  memory_level: 0.40

simulation:
  warm_up_time: 600
  simulation_time: 3600

network_path:
  network: "/home/miguel/6.Projects/Thesis/sumo/net/Koh/1st.net.xml"

duarouter:
  routing_algorithm: "CH"
  random_factor: 100
  max_attempts: 25
  n_threads: 7
  n_routes_per_OD: 5

stopping_rule:
  max_episodes: 100
  tolerance_stopping_rule: 0.01
  k_no_change: 3

demand_calibration:
  heuristic_veh_km_hour_initial_guess: 100
  target_congestion_ratio: 0.6
  tolerance_demand_calibration: 0.1
  k_demand_calib: 1

interval_time:
  time_interval_heuristic: 0.5
  fixed_time_interval: false
  fixed_time_min: 15

randomtrips:
  max_size_od_space: 10
  fringe_factor: 50

due_convergence: 
  threshold_density: 10
  duaIterate_max_iterations: 10
  duaIterate_step_length: 0.1

mode_and_flags:
  have_precomputed_routes: false
  last_episode_gui_BM: false
  last_episode_gui_duaIterate: false